# Generated by Django 2.0.9 on 2024-03-16 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Calendar', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exan_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='External_Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='internal_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='own_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NLP.collage')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NLP.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Research_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Abstract', models.CharField(default='', max_length=1000)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('email', models.CharField(default=1, max_length=100)),
                ('phone', models.CharField(default=1, max_length=100)),
                ('COLLAGE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.collage')),
                ('COURSE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.Course')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.Login')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.Course')),
            ],
        ),
        migrations.AddField(
            model_name='internal_mark',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.student'),
        ),
        migrations.AddField(
            model_name='internal_mark',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.subject'),
        ),
        migrations.AddField(
            model_name='external_mark',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.student'),
        ),
        migrations.AddField(
            model_name='external_mark',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.subject'),
        ),
        migrations.AddField(
            model_name='exan_timetable',
            name='SUBJECT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.subject'),
        ),
        migrations.AddField(
            model_name='collage',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.Login'),
        ),
        migrations.AddField(
            model_name='academic_calendar',
            name='COURSE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NLP.Course'),
        ),
    ]
