# Generated by Django 2.0.9 on 2024-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='own_list',
            name='fee',
            field=models.CharField(default='', max_length=100),
        ),
    ]
