# Generated by Django 2.0.9 on 2024-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0002_own_list_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Stream',
            field=models.CharField(default='', max_length=100),
        ),
    ]
