# Generated by Django 2.0.9 on 2024-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0003_course_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
