# Generated by Django 2.0.9 on 2024-04-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0004_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coursecode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
